### ISSUE TITLE
LaTeX Error: File `dnd.sty' not found when using 

### ISSUE THREAD

**Issue by jamespblloyd-uwa** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#108]
I found an error message in Overleaf when loading the examples in /characters that were not "-plain", such as `aaliyah.tex`. 

```LaTeX Error: File `dnd.sty' not found.```

The error was listed next to this line in the Overleaf:
`\usepackage{ifthen}`
But was below this line:
`\usepackage[justified]{dnd}`

Not sure what I am doing wrong or if this is a bug, but I followed the instructions the best that I could.

**Comment by matsavage** [comment]
Hi @jamespblloyd-uwa thanks for your interest in the project.

I have just had a go with the most recent release in overleaf and all works as expected: https://www.overleaf.com/read/pwbcfsjkhjwk#bf2611

The settings I changed were LuaLaTeX and the main document path, but I’m not sure the document path was required. 
![image](https://github.com/user-attachments/assets/e532357f-96ba-45ef-a6e9-932b5f092aaa)

Feel free to copy the overleaf project if that’s easier for you, or I can transfer ownership, if there is something different to what you’re doing it might be worth updating the documentation.

**Comment by matsavage** [comment]
Just thinking back, did you download a zip of the project from the [releases](https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/releases) section, or download from the cline project dialog.

There is a zip for overleaf in the releases, where I package in the [DnD Template](https://github.com/rpgtex/DND-5e-LaTeX-Template) which is required for the other styling.

**Comment by jamespblloyd-uwa** [comment]
Huzzah! That fixed it! I was indeed using the zip from the clone project dialog wrongly thinking that was what I was supposed to do. I completely missed the Releases section. My apologies for that. 

Thank you for making such a nice tool (and open source). I am excited to play around with it some more (I do some simple coding for my work in biology, but new to LaTex) but I am interested in how it can help with my hobby of D&D and Tales of the Valiant!

**Comment by matsavage** [comment]
Ah that makes sense.

For the sheet to work with the fancy DnD styles it needs the other LaTeX template too so we have the package them up to work in Overleaf.

**Comment by matsavage** [comment]
Just looking at Tales of the Valiant now, is it one of the non-Wizards 5e clones?

It could be possible to use the basis of this for an alternate sheet.

**Comment by jamespblloyd-uwa** [comment]
Tales of the Valiant is a non-Wizards 5e clone, designed to be fully backwards compatible. It has made a lot of the same changes as what WotC is doing with 5.5e (or 2024 rules) but perhaps less radical in some respects to keep to the core of the 5e we all currently love. 

It has largely been a reworking of the classes and like 5.5e, has made it so that all classes get a sub-class at the same level. But for a charactersheet these can just be treated as third party/homebrew classes. 

The other changes it has made, which are more of an issue for compatibility with existing charactersheets is
1. Splitting of Race into Lineage and Heritage. 
2. Renaming of some aspects like Feats to Talents and Spell Levels to Spell Circles 

For me splitting Race (to become Species in 5.5e later this year from WotC) into two aspects makes sense. So you have more flexibility in building your character. Lineage reflects appearance from biology and certain traits, while Heritage describes how you were raised and your culture. 

I was thinking to see how a small modification could be made to 1) change the appearance of the charactersheet to not use the official D&D assets like logos but otherwise be similar and 2) change Race to Lineage & Heritage. But not sure when I will get time to do that.
