### ISSUE TITLE
Editable fields

### ISSUE THREAD

**Issue by Tesla2000** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#110]
I am very grateful for creating this template. The only thing that I noticed is different from the original is an ability to interactively edit field in .pdf. I would greatly appretiate this function being added as it would allow editing pdf without having to recompile the entire file. 
Thank you in advance

**Comment by matsavage** [comment]
Hi @Tesla2000, sorry, but this is functionality which is not possible with LaTeX, so will also be impossible with this project.

If you are looking to modify the background or colours of the base character sheet, whilst retaining the form fields, you might be able to do something like that with a PDF editor?
