### ISSUE TITLE
cant compile character sheet at all.

### ISSUE THREAD

**Issue by bjamey** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#13]
I keep getting the following error " LaTeX Error: File `dndtemplate.sty' not found." even though I followed all the setup instructions / cloned the repo to a local folder.
Made a character by coping the dagmar.tex file in the characters folder then editing as needed.

Trying to work this out but no joy. If this is not the right place to ask this please tell me where.

ignore this. idiot me just moved the file out of the char directory into the root dir and everything now works.

**Comment by matsavage** [comment]
hi, did you fix the error? I was going to look into this today
