### ISSUE TITLE
Document compiles but all the text is at the bottom left of the page

### ISSUE THREAD

**Issue by Abi45** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#14]
Hello, first of all thanks for making this.  
I use texmaker on ubuntu, and initially I was having the font path problem mentioned in the other issue, but I circumvented that by copying the fonts in the same folder as the dagmar.tex file, and removing "Path=template/fonts/," in the character-sheet-setting.tex file (I don't know if that was the wrong thing to do, but the document would return the fontsec path error before. and after I did that change it started compiling.)

At first I though the document was compiling with non of the text but then I noticed it was all bunched together at the bottom left corner of the page (see attached). It does this for the first three pages and then appears to be normal from "Features, Magic Items and Spells".

Any idea what might be causing this and how to fix it? A quick google search didn't help me but maybe I wasn't searching for the right things.  

[character.pdf](https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/files/9263171/character.pdf)

**Comment by matsavage** [comment]
Hi @Abi45 this the text issue sounds like something that has cropped up before: https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/issues/7 and is to do with the default version of Ghostscript which comes with Ubuntu

I should have a go at cracking this font problem, it's been a while since I have done anything on this repo, as my group changed to Pathfinder, the font path issue also causes complications with the [dungeonsheets](https://github.com/canismarko/dungeon-sheets) package (which was part of the reason I made this)

Please let me know how you get on with the issue linked above. I am on holiday from tomorrow and won't have access to a computer for a week, but can probably have a look after that if you're still having problems

Mat

**Comment by Abi45** [comment]
Ah perfect! That worked great, I did have a look at the already existing issues, but I'm not that familiar with github and I didn't realise it was only showing me the open issues, not all the pre-existing ones.

I do have another question for whenever you see this, I'm trying to make it into a4 format, I have replaced "letterpaper" by "a4paper" in the document class, which worked, but I was wondering where would I go, and how would I proceed to modify the size of the boxes to scale to the new size (for now there is an empty space at the bottom of the page).

In the mean time, I'll try to figure this out myself and update if I do.

**Comment by matsavage** [comment]
Hi @Abi45 great to see you got that working!

Options for this would be either:
* If you are happy with the width, you could insert a horizontal space above the start of each page to centre it in the page
* Put the whole page inside of a float, and then play with the scale factor

This second choice is much more complex, and honestly I haven't had a look at this code in about 2 years, so you would be a little on your own there. I tried to have a quick go, but was running into issues with Ghostscript and have a lot on, would be a while before I could commit some real time to having a look.

**Comment by Abi45** [comment]
Hi @matsavage, thanks for providing me with some options, I'll try to play around and see if that works. Thanks for taking the time to answer me!

**Comment by matsavage** [comment]
If you get something working, I'd be interested to see it, could be worth raising a PR to give other people more options, or any tips on getting things set up more easily, having a go yesterday made me realize how user-unfriendly some elements of this project are

**Comment by Abi45** [comment]
Hi, I haven't had any progress as I got busy, and when i tried again it turns out that since I updated to the latest release of ubuntu, the pstricks graphics don't show up for some reason...
But anyway that's not what I want to say, I saw that there is a small typo in the template/character-sheet/template-text.tex on line 25, it should be "Intelligence" instead of "inteligence". I would edit it myself but I have no idea how to use github and if I can even do that, would I click "Edit the file in your fork of this project" and would that correct it just for me or for everybody?

**Comment by matsavage** [comment]
@Abi45 No worries, I have fixed the typo, no need to learn github for that one

Let me know if you come across more issues getting this set up
