### ISSUE TITLE
Nix Flake

### ISSUE THREAD

**Issue by Soispha** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#16]
As this latex project requires xetex, custom fonts and pstricks to compile it's quite challenging, especially for inexperienced people. 
Encountering these issues, I've written a [Nix Flake](https://github.com/Soispha/DND-5e-LaTeX-Character-Sheet-Template/tree/nix_flake), to simplify the build process considerably. See the commit message and the readme for a quick explanation what this is and what it does.
If you would like to add this, let me know and I'll open a pull request, otherwise I'm fine with keeping my fork up to date.

**Comment by matsavage** [comment]
Okay, so I had a look at this, and I managed to get the NixOS part working in a GitHub action, so it will be possible to check that this part continues to work. I have raised a PR to bring this into your work, with the intention of bringing the NixOS code and the action into `main` in a future PR:
https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/pull/17

From my understanding NixOS is building a PDF when this is executed, I would also like this to be available to download, from the code segment I have tagged you in, would you be able to determine where the PDF will be written to by NixOS.

**Comment by Soispha** [comment]
I am very short on time lately, but these changes all sound rather reasonable. I'll open a new pr, when I've gotten around to update everything.

**Comment by matsavage** [comment]
No rushon any of this, thaks for the comment on the automation, the result is in the `result` directory, and with a bit of work it's able to be downloaded, see: https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/actions/runs/4956982864 
The artifact at the bottom of the page contains the genersted pdf file

However this is a blank character sheet, not sure if the issue stems from the flake or the repo. One nice thing would be for the flake to save the LaTeX .log output file somewhere so it can be included in the artifact, so issues can be debugged when they arise

**Comment by matsavage** [comment]
Turns out this was on me, recent changes to do the calculations have changed more than I expected, I need to build a decent makefile and update some example characters.

Busy could of weeks coming up, but will have a go at some point
