### ISSUE TITLE
Half caster spell sheet

### ISSUE THREAD

**Issue by matsavage** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#47]
Thanks very much very much for merging this!!!

I hope I can use this place also two questions - 

1. What would it take to adapt your template to a4paper?
2. What would it take to adapt your spells list to fit, e.g., a cleric's spell list? I know dungeonsheets with the official dnd form uses a half caster's sheet for that.

_Originally posted by @PJBrs in https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/issues/45#issuecomment-1880114945_

**Comment by matsavage** [comment]
@PJBrs I have created a branch on this issue and pushed the template to it: 

https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/blob/232917e7a5151ee7bfef4414f2f03815b6c77338/template/half-spell-sheet/template.tex#L1-L10

**Comment by matsavage** [comment]
@PJBrs I have completed the work on moving the template into separate files, would you be able to have a go at lining up the text boxes for the spells and colour switches for the proficiency markers.

Tip for the lining up is determine the position of the first box, then use the fixed offset to calculate the positions of the others.

**Comment by PJBrs** [comment]
Hmmm... The locations of the various boxes seems rather precise... Would there be any way to have that same precision, based on the original halfcaster sheet?

**Comment by PJBrs** [comment]
Nevermind, I think the numbers are pretty round --> https://github.com/PJBrs/DND-5e-LaTeX-Character-Sheet-Template/commit/b72294861d80518fe02c360c76cc44fa885b383b

**Comment by PJBrs** [comment]
Hmm... I think I did it :-)

But I didn't really test it fully...

**Comment by matsavage** [comment]
All looking good, thanks for picking up, I am busy the next couple of weekends, so may end up being a while before I can do this myself.

To make the spell prepared colours render, you will have to update the colours of the fill for the circle next to the spell line, they can be found as in here:

https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/blob/6303514e0da36013a44ba3070f2afbe1aef0f4ce/template/half-spell-sheet/spell-slots.tex#L144-L155

I copy pasted these in the order they appeared from the template, so there is no 100% guarantee they are in order, but they should mostly be pretty close.

Coordinates for columns 2/3 should match in the vertical, but be different in the horizontal.

**Comment by PJBrs** [comment]
I think it's quite alright now! Needs more testing with a character with over 11 cantrips, over 26 level 1 spells, and over 19 spells for levels  3, 4, and 5 each.

To make this work with dungeonsheets, you need a small patch as follows (and maybe more, I just wanted to test):
```
diff --git a/dungeonsheets/latex.py b/dungeonsheets/latex.py
index 2db9423..20f1918 100644
--- a/dungeonsheets/latex.py
+++ b/dungeonsheets/latex.py
@@ -282,9 +282,10 @@ def msavage_spell_info(char):
                        'EighthLevelSpell',
                        'NinthLevelSpell']
     sheet_spaces = dict(zip(level_names,
-                    [8, 13, 13, 13, 13, 9, 9, 9, 7, 7]))
+                    [11, 26, 19, 19, 19, 19, 9, 9, 7, 7]))
     comp_letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", 
-                  "L", "M"]
+                  "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", 
+                  "W", "X", "Y", "Z"]
     spellList = char.spell_casting_info["list"]
     for k, v in spellList.items():
         slots_max = sheet_spaces[k]
```
And you need to change \renderspellsheet to \renderhalfspellsheet in dungeonsheets/forms/MSavage_template.tex.

Below picture is for my current character:
![image](https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/assets/5177219/37e119e0-3e5b-4dee-8574-7639bcb6c4d7)

**Comment by PJBrs** [comment]
... Anyway, I'll do some more thorough testing when I get around it. Let me know if anything still is missing, if you want to turn this into a pull request, and if the commit messages need a bit more fleshing out. Or you can just grab these patches yourself, obviously.

In the meantime, suppose you had some time, it would be great if you'd test my dungeonsheets branch over here against your latest dndtemplate:

https://github.com/PJBrs/dungeon-sheets/tree/MSavage-latex-template

I'd like to see it have a little bit more testing before I open another pull request with dungeonsheets.

**Comment by matsavage** [comment]
Looks good, my suggestions would be:* Raise PR in dungeonsheets without the half caster page* Raise PR in this report* When this work is merged in, submit another PR to dungeonsheets with the half caster page. That way there will be no period one is dependent on something not in the other. This looks very good though, either you can raise a PR or I can, but I’ll want to check the spells/prepared markers and it’ll be middle of next week before I get a chance.On 16 Jan 2024, at 19:12, PJBrs ***@***.***> wrote:﻿
... Anyway, I'll do some more thorough testing when I get around it. Let me know if anything still is missing, if you want to turn this into a pull request, and if the commit messages need a bit more fleshing out. Or you can just grab these patches yourself, obviously.
In the meantime, suppose you had some time, it would be great if you'd test my dungeonsheets branch over here against your latest dndtemplate:
https://github.com/PJBrs/dungeon-sheets/tree/MSavage-latex-template
I'd like to see it have a little bit more testing before I open another pull request with dungeonsheets.

**Comment by PJBrs** [comment]
OK! In that case, it'd be great if you could test my https://github.com/PJBrs/dungeon-sheets/tree/MSavage-latex-template tree, and if you deem it successful, I'll raise that PR in dungeonsheets. I'll add the halfcastersheet PR over here after that, and then I'll figure out how to properly implement it over at dungeonsheets. Thanks!

**Comment by matsavage** [comment]
I’ll try and have a go, but have work engagements the next 3 evenings.The reason I suggest doing things this way is that it’s usually best to keep PRs to one complete change at a time, or it can get hard to determine which code changes correspond to which feature.I have some ideas to improve the testing of this library, I didn’t like that it managed to get out of sync with dungeonsheetsSent from my iPhoneOn 16 Jan 2024, at 19:45, PJBrs ***@***.***> wrote:﻿
OK! In that case, it'd be great if you could test my https://github.com/PJBrs/dungeon-sheets/tree/MSavage-latex-template tree, and if you deem it successful, I'll raise that PR in dungeonsheets. I'll add the halfcastersheet PR over here after that, and then I'll figure out how to properly implement it over at dungeonsheets. Thanks!
