### ISSUE TITLE
Text issues when compiling locally

### ISSUE THREAD

**Issue by Tim-Jackins** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#7]
Whenever I try to compile the pdf locally the rpgtex parts seem to work but the character sheet parts don't. All the text is crammed into the bottom left of the page.

I have no doubt this is because I have setup stuff wrong but was wondering if you had any ideas. Thanks for your time!

![Screenshot from 2021-05-27 16-28-00](https://user-images.githubusercontent.com/30958382/119893880-ea36c180-bf09-11eb-878d-17b35f7470e3.png)

Logs

<details>
        <summary>The output from <code>xelatex dagmar.tex</code></summary>

This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./dagmar.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/bk10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def)))
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/home/jack/texmf/tex/latex/dnd/dnd.sty
(/home/jack/texmf/tex/latex/dnd/dndoptions.clo
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)

Package dnd Warning: Package option "layout" will default to false in 1.0.0.

) (/home/jack/texmf/tex/latex/dnd/dndcore.def
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty)
(/usr/share/texlive/texmf-dist/tex/latex/colortbl/colortbl.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/xetex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/enumitem/enumitem.sty)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)
(/usr/share/texlive/texmf-dist/tex/latex/was/gensymb.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hang/hang.sty)
(/usr/share/texlive/texmf-dist/tex/latex/numprint/numprint.sty
No configuration file `numprint.cfg' found.)
(/usr/share/texlive/texmf-dist/tex/latex/tools/tabularx.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcolorbox.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.t
ex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def
(/usr/share/texlive/texmf-dist/tex/latex/ms/everyshi.sty))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/pgf.revision.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t
ex)) (/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-xetex.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.de
f))))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.
tex)) (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonomet
ric.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.cod
e.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerari
thmetics.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.
code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code
.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformation
s.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.t
ex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.
tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.te
x)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.c
ode.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.
tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
) (/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65
.sty)
(/usr/share/texlive/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18
.sty)) (/usr/share/texlive/texmf-dist/tex/latex/tools/verbatim.sty)
(/usr/share/texlive/texmf-dist/tex/latex/environ/environ.sty
(/usr/share/texlive/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbbreakable.code.tex
Library (tcolorbox): 'tcbbreakable.code.tex' version '4.22'
) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskins.code.tex
Library (tcolorbox): 'tcbskins.code.tex' version '4.22'
(/usr/share/texlive/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)))
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex

(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers
.code.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
)
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbskinsjigsaw.code.tex
Library (tcolorbox): 'tcbskinsjigsaw.code.tex' version '4.22'
)) (/usr/share/texlive/texmf-dist/tex/latex/tcolorbox/tcbxparse.code.tex
Library (tcolorbox): 'tcbxparse.code.tex' version '4.22'
)) (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifvtex.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/microtype/microtype.sty
(/usr/share/texlive/texmf-dist/tex/latex/microtype/microtype-xetex.def)
(/usr/share/texlive/texmf-dist/tex/latex/microtype/microtype.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/ragged2e/ragged2e.sty
(/usr/share/texlive/texmf-dist/tex/latex/ms/everysel.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tocloft/tocloft.sty)
(/usr/share/texlive/texmf-dist/tex/latex/titlesec/titlesec.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ms/multitoc.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/multicol.sty

Package multicol Warning: May not work with the twocolumn option on input line 
141.

) (/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty))
(/home/jack/texmf/tex/latex/dnd/lib/compat.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndutility.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndcolors.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndfonts.sty
(/usr/share/texlive/texmf-dist/tex/latex/lettrine/lettrine.sty
(/usr/share/texlive/texmf-dist/tex/generic/minifp/minifp.sty)
Loading lettrine.cfg
(/usr/share/texlive/texmf-dist/tex/latex/lettrine/lettrine.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/cfr-initials/Royal.sty
(/usr/share/texlive/texmf-dist/tex/latex/initials/RoyalIn.fd))
(/usr/share/texlive/texmf-dist/tex/latex/contour/contour.sty
Loading configuration file `contour.cfg'.
(/usr/share/texlive/texmf-dist/tex/latex/contour/contour.cfg)
contour: Using driver file `dvips.cnt'.
(/usr/share/texlive/texmf-dist/tex/latex/contour/dvips.cnt))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/bookman.sty)
(/usr/share/texlive/texmf-dist/tex/latex/gillius/gillius2.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifxetex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifluatex.sty)
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty

LaTeX Font Warning: Font shape `TU/pbk/m/n' undefined
(Font)              using `TU/lmr/m/n' instead on input line 112.

) (/usr/share/texlive/texmf-dist/tex/latex/fontaxes/fontaxes.sty))
(/usr/share/texlive/texmf-dist/tex/latex/kpfonts/kpfonts.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pbk.fd)))
(/home/jack/texmf/tex/latex/dnd/lib/dndstrings.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dnddeprecated.sty
(/usr/share/texlive/texmf-dist/tex/latex/keycommand/keycommand.sty
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty

Package etex Warning: Extended allocation already in use.
(etex)                etex.sty code will not be used.
(etex)                To force etex package to load, add
(etex)                \RequirePackage{etex}
(etex)                at the start of the document.

) (/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp.sty
`Fixed Point Package', Version 0.8, April 2, 1995 (C) Michael Mehlich
(/usr/share/texlive/texmf-dist/tex/latex/fp/defpattern.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-basic.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-addons.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-snap.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-exp.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-trigo.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-pas.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-random.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-eqn.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-upn.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fp/fp-eval.sty))
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex)))
(/home/jack/texmf/tex/latex/dnd/lib/dndcomment.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndheader.sty
(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty))
(/home/jack/texmf/tex/latex/dnd/lib/dndmonster.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndreadaloud.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndsections.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndsidebar.sty)
(/home/jack/texmf/tex/latex/dnd/lib/dndtable.sty)))
(/home/jack/texmf/tex/latex/dnd/lib/dndtoc.sty
(/usr/share/texlive/texmf-dist/tex/latex/titlesec/titletoc.sty))
(/usr/share/texlive/texmf-dist/tex/latex/pstricks/pstricks.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/pst-xkey.tex)
(/usr/share/texlive/texmf-dist/tex/generic/pstricks/pstricks.tex
(/usr/share/texlive/texmf-dist/tex/generic/pstricks/pst-fp.tex
`pst-fp' v0.05, 2010/01/17 (hv))
`PSTricks' v2.97  <2019/05/11> (tvz,hv)
(/usr/share/texlive/texmf-dist/tex/xelatex/xetex-pstricks/pstricks.con
(/usr/share/texlive/texmf-dist/tex/generic/pstricks/config/xdvipdfmx.cfg))
(/usr/share/texlive/texmf-dist/tex/xelatex/xetex-pstricks/pstricks.con
(/usr/share/texlive/texmf-dist/tex/generic/pstricks/config/xdvipdfmx.cfg
Using PSTricks configuration for XeTeX+xdvipdfmx
))) (/usr/share/texlive/texmf-dist/tex/generic/pstricks/pst-fp.tex)
>>> Loading XeTeX special macros
(/usr/share/texlive/texmf-dist/tex/generic/pstricks/pstricks-xetex.def))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/switch.def)
(/usr/share/texlive/texmf-dist/tex/generic/babel-english/UKenglish.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/xebabel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def))))))
(../character-sheet-settings.tex) (../template/character-sheet-commands.tex)
(/home/jack/texmf/tex/latex/dnd/lib/languages/italian.sty)
(/home/jack/texmf/tex/latex/dnd/lib/languages/japanese.sty)
(/home/jack/texmf/tex/latex/dnd/lib/languages/ngerman.sty)
(/home/jack/texmf/tex/latex/dnd/lib/languages/russian.sty)
(/home/jack/texmf/tex/latex/dnd/lib/languages/spanish.sty) (./dagmar.aux)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
ABD: EveryShipout initializing macros
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
ABD: EverySelectfont initializing macros (../template/character-sheet.tex
(../template/character-sheet/header.tex) (../template/character-sheet/stats.tex
) (../template/character-sheet/battle-stats.tex)
(../template/character-sheet/outlines.tex)
(../template/character-sheet/money-outlines.tex)
(../template/character-sheet/traits.tex)
(../template/character-sheet/player-input.tex

LaTeX Font Warning: Font shape `TU/GilliusADFNoTwo-LF/m/n' undefined
(Font)              using `TU/lmr/m/n' instead on input line 92.

(/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-LatinModernRoman.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-cmr.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1pbk.fd)
(/usr/share/texlive/texmf-dist/tex/latex/kpfonts/t1jkpss.fd))
(../template/character-sheet/proficiency-markers.tex)
(../template/character-sheet/template-text.tex
(/usr/share/texlive/texmf-dist/tex/latex/kpfonts/ts1jkpss.fd))
Overfull \hbox (19.37222pt too wide) detected at line 21
 [] 
) (../template/spell-sheet.tex (../template/spell-sheet/header.tex)
(../template/spell-sheet/outlines.tex)
(../template/spell-sheet/spell-level-headers.tex)
(../template/spell-sheet/player-input.tex)
(../template/spell-sheet/spell-slots.tex)
(../template/spell-sheet/template-text.tex)
Overfull \hbox (19.37222pt too wide) detected at line 18
 [] 
)
Underfull \vbox (badness 10000) has occurred while \output is active [1]
[2GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
]
contour: Using 32 copies for `Features,' on input line 253.
contour: Using 32 copies for `Magic' on input line 253.
contour: Using 32 copies for `Items' on input line 253.
contour: Using 32 copies for `and' on input line 253.
contour: Using 32 copies for `Spells' on input line 253.
(/usr/share/texlive/texmf-dist/tex/latex/gillius/T1GilliusADFNoTwo-LF.fd)
[3]
Underfull \vbox (badness 2460) has occurred while \output is active [4]
[5] [6] [7] [8] (./dagmar.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 )
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
(see the transcript file for additional information)
Output written on dagmar.pdf (8 pages).
Transcript written on dagmar.log.
</details>

**Comment by Tim-Jackins** [comment]
Thanks! This looks helpful I'll try it out

**Comment by matsavage** [comment]
@Tim-Jackins did you get anywhere with this?

**Comment by Tim-Jackins** [comment]
Yes worked like a charm!

**Comment by matsavage** [comment]
Great to hear it, enjoy the sheet, any feedback would be great, I think you're the first other person to use it

**Comment by Tim-Jackins** [comment]
I love it, in fact I'm planning on building it into this https://github.com/canismarko/dungeon-sheets! It's what I currently use for dnd character sheet stuff. I'm assuming this is open source didn't see a license?

**Comment by matsavage** [comment]
haha, I have spoken to the owner about the repo about doing that, and have updated the rpgtex mode of that already, but lockdown has eased a little in the UK so I'm finding less time to do it.

My feeling is that I would need to sort of change how this code is packaged to make it more of a module that could be imported, might be worth seeing if we can get the three of us into a chat to see how we might do things.

It's open source as far as I am concerned, I just don't know the status since obviously the sheet itself isn't my property.

**Comment by Tim-Jackins** [comment]
Any plans to add the second page of [this](https://media.wizards.com/2016/dnd/downloads/5E_CharacterSheet_Fillable.pdf)?

**Comment by matsavage** [comment]
I certainly can, been on my radar for a while, I'm off on holiday this Friday though, so it'll be a week or two

**Comment by matsavage** [comment]
also my d&d game ended and we're just starting on pathfinder 2e now, still something I want to get done

**Comment by Tim-Jackins** [comment]
If you could provide me with some info as to how to do it I'd be happy to try to make it myself?

**Comment by matsavage** [comment]
I just imported the non form-fillable one into Inkscape and there is an export as LaTeX option. From there I just sort of changed the colour of elements to find out which piece is which, and separated out related bits of the sheet into different files until I had figured out what they all did.

**Comment by Tim-Jackins** [comment]
I'll see what I can do.

**Comment by matsavage** [comment]
https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/compare/backstory-page

I've done the inkscape step here, just needs breaking out into sections based on what each of the boxes are

**Comment by Tim-Jackins** [comment]
Cool, I'll take a crack this weekend

**Comment by matsavage** [comment]
other than that it's `\rputs` to line text boxes up with the outlines, I think there may be a better way to do this though, as it's easy to allow the text to expand too far etc

**Comment by Tim-Jackins** [comment]
Got halfway through it.  Hoping to finish in the coming week but thought should post what I have so far https://github.com/Tim-Jackins/DND-5e-LaTeX-Character-Sheet-Template/tree/backstory-page

**Comment by matsavage** [comment]
Looking good, just a couple of comments:

- When running locally, the top position of the appearance block looks to be a bit too high

![image](https://user-images.githubusercontent.com/20909362/124236134-041d8280-db0e-11eb-9489-1e76c5c10577.png)

- The header for the existing pages has an accent colour, which is missing in the backstory page, I think these lines are easy enough to pick out, as they are a different thickness to the other ones
![image](https://user-images.githubusercontent.com/20909362/124236262-24e5d800-db0e-11eb-9e0c-d5da623a07f7.png)

Looking really great so far though!

**Comment by Tim-Jackins** [comment]
@matsavage Finished this up! Let me know if you see any issues and checkout #8
